// Generated by scripts/evolution/import-images.py: the Gotomon that have an evolved picture
// (public/assets/images/monsters/evo/<id>.webp). Do not edit by hand.
export const EVOLVED_IDS = Object.freeze(["AOM-E01", "AOM-E10", "CAN-E010", "CHN-E010", "EGY-E010", "FUK-E01", "GF-E01", "GNM-E01", "HKD-E01", "HKD-E10", "HYG-E01", "KOCH-E01", "NGT-E10", "OKY-E01", "OSK-E01", "SG-E10", "TKY-E01", "TOKU-E10", "TTR-E10", "TYM-E01"]);
