// Generated by scripts/evolution/import-images.py: the Gotomon that have an evolved picture
// (public/assets/images/monsters/evo/<id>.webp). Do not edit by hand.
export const EVOLVED_IDS = Object.freeze(["AOM-E10", "CAN-E010", "CHN-E010", "EGY-E010", "HKD-E01", "HKD-E10", "NGT-E10", "SG-E10", "TOKU-E10", "TTR-E10"]);
