// Presentation metadata stays outside the stable v1 registry contract.
// `arcade` games draw their own real-time world; `paced` games offer ゆっくり.
export const gameExperiences = Object.freeze({
  mathSprint: { genre: '算数', difficulty: '入門', time: '約1分', icon: '➜', scene: 'race', arcade: true, paced: true, badge: 'NEW',
    description: '計算してハードルをジャンプ！ ゴールまで走りぬけ。', goal: '答えるとジャンプ。止まらず走ってタイムを縮めよう。', skill: 'ゴトモンダッシュ', effect: '5秒間スピードアップ', unit: 'm', color: '#177a69',
    howTo: ['ハードルの計算に答えると、相棒がジャンプ！', '早く答えるほど止まらずに走れる。まちがえても前へ進めるよ。', '3回正解すると「ゴトモンダッシュ」が自動で発動！'],
    controlsNote: 'キーボードの数字とEnterでも遊べます。' },
  mathInvader: { genre: '算数', difficulty: 'ふつう', time: '約2分', icon: '✦', scene: 'shoot', arcade: true, paced: true, badge: 'NEW',
    description: '答えの数字をうつと、その敵に命中！ 最後はボス戦。', goal: '答えをうつ → 同じ答えの敵に命中！', skill: 'スター連射', effect: '次の3発を強化', unit: '撃退', color: '#346bab',
    howTo: ['落ちてくる敵の計算を見る。', '答えの数字を入れて「うつ！」。同じ答えの敵に自動で命中！', 'バリアまで来ても大丈夫。最後に出てくるボスをたおそう！'],
    controlsNote: 'キーボードの数字とEnterでも遊べます。敵をタップすると、ねらいを決められます。' },
  englishChoice: { genre: '英語', difficulty: '入門', time: '約1分', icon: '◇', scene: 'treasure',
    description: '安全？レア？扉を開けて4部屋の宝探し。', goal: '意味の合う扉を開けて、宝箱を集めよう。', skill: 'おたからフィーバー', effect: '宝箱の鍵を補充', unit: '箱', color: '#7153a4',
    howTo: ['部屋ごとに安全な道かレアな道を選ぶ。', '英単語の意味に合う扉を一つ選ぶ。', '正解して宝を集め、4部屋の先を目指す。'] },
  sentenceOrder: { genre: '国語', difficulty: 'ふつう', time: '約2分', icon: '▰', scene: 'bridge',
    description: '文節を動かして、相棒の橋をつなごう。', goal: '文節を並べる → 橋がつながる → 相棒が渡る！', skill: '虹のかけ橋', effect: '次の橋を虹色に', unit: '橋', color: '#39774c',
    howTo: ['言葉の板をドラッグするか、選んで左右に動かす。', '自然な文に並んだら「これで決定」を押す。', '困ったら先頭のヒントを使える。'] },
  timedChoice: { genre: 'ことば', difficulty: '挑戦', time: '約1分', icon: '◷', scene: 'lantern',
    description: '光を守り、5つの灯台に分けよう。', goal: '光を分けて灯台へ。正解で相棒の光が回復！', skill: 'ひかりフィーバー', effect: '光回復・減少を緩和', unit: '灯', color: '#ad6726',
    howTo: ['通常プレイでは各問題の制限時間は5秒。', '表示された言葉の読みを一つ選ぶ。', '光の配分を選び、灯台をともす。復習には時間制限がない。'] },
  multiSelect: { genre: '理科・算数ほか', difficulty: 'ふつう', time: '約2分', icon: '✧', scene: 'craft',
    description: '合う星をつなぎ、3つの星座を完成。', goal: '正しい素材を集めて、相棒と星座をつくろう。', skill: '星座のきらめき', effect: '次の星が1.5倍', unit: '星座', color: '#347b87',
    howTo: ['あてはまる答えをすべて選んで「決定」を押す。', '正しく選べた数で星の光が増える。', '光を入れるルートを選び、3つの星座を完成させる。'] },
  asyncChoice: { genre: '教科ミックス', difficulty: 'ふつう', time: '約2分', icon: '⌖', scene: 'explore',
    description: '5地点の順路を選び、手がかりでレア発見。', goal: '林道・海辺の手がかりを遺跡で使おう！', skill: '発見フィーバー', effect: '手がかり＋発見強化', unit: '発見', color: '#447b67',
    howTo: ['次に調べる場所を選ぶ。', '出てきた問題の答えを一つ選ぶ。', '手がかりを集めて、5地点の発見を増やす。'] },
  kanjiDefense: { genre: '漢字の読み', difficulty: '挑戦', time: '約3分', icon: '♜', scene: 'defend', arcade: true, paced: true, badge: 'NEW',
    description: '読みを入力して、せまるモンスターを撃退！', goal: '読みを入力 → 同じ読みのモンスターに命中！', skill: '相棒エール', effect: '次の3正解で得点UP', unit: '撃退', color: '#ac5838',
    howTo: ['モンスターが持つ漢字の読みを考える。', '読みをひらがなで入れて「こうげき」。同じ読みのモンスターに自動で命中！', '門まで来ても大丈夫。読みを見て、次に生かそう。'],
    controlsNote: 'モンスターをタップすると、ねらいを決められます。' },
});
