// Presentation metadata stays outside the stable v1 registry contract.
// `arcade` games draw their own real-time world; `paced` games offer ゆっくり.
export const gameExperiences = Object.freeze({
  mathSprint: { genre: '算数', difficulty: '入門', time: '約1分', icon: '➜', scene: 'race', arcade: true, paced: true, badge: 'NEW',
    description: '計算してハードルをジャンプ！ ゴールまで走りぬけ。', goal: '答えるとジャンプ。止まらず走ってタイムを縮めよう。', skill: 'ゴトモンダッシュ', effect: '5秒間スピードアップ', unit: 'm', color: '#177a69',
    howTo: ['ハードルの計算に答えると、相棒がジャンプ！', '早く答えるほど止まらずに走れる。まちがえても前へ進めるよ。', '3回正解すると「ゴトモンダッシュ」が自動で発動！'],
    controlsNote: 'キーボードの数字とEnterでも遊べます。' },
  mathInvader: { genre: '算数', difficulty: 'ふつう', time: '約2分', icon: '✦', scene: 'shoot', arcade: true, paced: true, badge: 'NEW',
    description: '答えの数字をうつと、その敵に命中！ 最後はボス戦。', goal: '答えをうつ → 同じ答えの敵に命中！', skill: 'スター連射', effect: '次の3発を強化', unit: '撃退', color: '#346bab',
    howTo: ['落ちてくる敵の計算を見る。', '答えの数字を入れて「うつ！」。同じ答えの敵に自動で命中！', 'バリアまで来ても大丈夫。最後に出てくるボスをたおそう！'],
    controlsNote: 'キーボードの数字とEnterでも遊べます。敵をタップすると、ねらいを決められます。' },
  englishChoice: { genre: '英語', difficulty: '入門', time: '約1分', icon: '◇', scene: 'chest', arcade: true, paced: true, badge: 'NEW',
    description: '英単語の意味の宝箱をキャッチ！', goal: '意味の合う宝箱をタップ → 宝箱が開く！', skill: 'おたからフィーバー', effect: '次の3回の宝を大きく', unit: '箱', color: '#7153a4',
    howTo: ['上に出た英単語を読む。', '意味の合う宝箱をタップ！ 早くキャッチするほど宝が大きい。', '下まで落ちても大丈夫。落ち着いて選ぼう。'],
    controlsNote: 'キーボードの1〜4でも選べます。' },
  sentenceOrder: { genre: '国語', difficulty: 'ふつう', time: '約2分', icon: '▰', scene: 'bridge', arcade: true, paced: true, badge: 'NEW',
    description: '次に来る言葉をタップして、相棒の橋をのばそう！', goal: '次の言葉をタップ → 橋が1まいのびる！', skill: '虹のかけ橋', effect: '次の3本の橋を虹色に', unit: '橋', color: '#39774c',
    howTo: ['川を流れる言葉の板から、文のはじめの言葉をタップ。', '合っていれば橋が1まいのびる。ちがう板は、ぷるっと川にもどるよ。', '同じところで2回まよったら、次の板が光って教えてくれる。'],
    controlsNote: 'キーボードの1〜4でも選べます。' },
  timedChoice: { genre: 'ことば', difficulty: '挑戦', time: '約1分', icon: '◷', scene: 'mole', arcade: true, paced: true, badge: 'NEW',
    description: '正しい読みのもぐらをたたこう！', goal: '読みの合うもぐらをタップ → ポカッ！', skill: 'もぐらフィーバー', effect: '次の3回の得点アップ', unit: '匹', color: '#ad6726',
    howTo: ['上に出た言葉の読みを考える。', '正しい読みを持ったもぐらをたたく！ 早いほど高得点。', 'もぐらは5秒で引っこむ。引っこんでも、答えを見て次へ行こう。'],
    controlsNote: 'キーボードの1〜4でもたたけます。「ゆっくり」では8秒です。' },
  multiSelect: { genre: '理科・算数ほか', difficulty: 'ふつう', time: '約2分', icon: '✧', scene: 'stars', arcade: true, paced: true, badge: 'NEW',
    description: 'お題に合う星をぜんぶ集めて、星座をつくろう。', goal: '合う星をタップで集める → 「あつめた！」で星座に！', skill: '星のきらめき', effect: '次の3つの星座を明るく', unit: '星座', color: '#347b87',
    howTo: ['夜空に出たお題を読む。', 'お題に合う星をぜんぶタップして集める。もう一度タップでもどせる。', '集めたら「あつめた！」。早く決めるほど星座が明るい。'],
    controlsNote: 'キーボードの1〜5で星を選び、Enterで決定できます。' },
  asyncChoice: { genre: '教科ミックス', difficulty: 'ふつう', time: '約2分', icon: '⌖', scene: 'mine', arcade: true, paced: true, badge: 'NEW',
    description: '正しい線路をえらんで、トロッコで宝の洞くつへ！', goal: '答えの線路をタップ → トロッコが洞くつへ！', skill: '発見フィーバー', effect: '次の3回の宝石アップ', unit: '発見', color: '#447b67',
    howTo: ['トロッコの前に出た問題を読む。', '答えの書かれた線路をタップ！ トロッコがその洞くつへ進む。', '分かれ道に着いても、トロッコは待っていてくれる。'],
    controlsNote: 'キーボードの1〜4でも選べます。' },
  photoRally: { genre: '漢字の読み', difficulty: 'ふつう', time: '約2分', icon: '📷', scene: 'photo', arcade: true, paced: true, badge: 'NEW',
    description: '顔を出したゴトモンの漢字を読んで、写真を撮ろう！', goal: '漢字の読みを選ぶ → パシャ！ アルバムに写真が入る', skill: 'シャッターチャンス', effect: '次の3まいの得点アップ', unit: 'まい', color: '#2f7d6d',
    howTo: ['行ったことのある場所で、ゴトモンがかくれた所から顔を出す。', 'ゴトモンが持っている文の、［　］の漢字の読みを選ぶとパシャ！ 早いほど★が多い。', '写真はアルバムに入り、ゴトモンの豆知識が読めるようになる。'],
    controlsNote: 'キーボードの1〜4でも選べます。' },
  proverbDetective: { genre: 'ことわざ', difficulty: 'ふつう', time: '約3分', icon: '🔍', scene: 'case', arcade: true, paced: true, manualNext: true, badge: 'NEW',
    description: '事件の話を読んで、ぴったりのことわざを見つけよう！', goal: '話を読む → ぴったりのことわざを指名 → 事件解決！', skill: 'ひらめき', effect: '次の3件の得点アップ', unit: '件', color: '#6b4e8a',
    howTo: ['ことわざの住人が、こまったできごとを話しに来る。', '話にぴったりのことわざを、4人の容疑者から指名しよう。ちがっても、その意味が分かるよ。', '虫めがねのヒントが出る前に当てると「名推理！」。解決したことわざは図鑑に印がつく。'],
    controlsNote: 'キーボードの1〜4でも選べます。' },
  gotomonFishing: { genre: '英語', difficulty: 'ふつう', time: '約3分', icon: '🎣', scene: 'fishing', arcade: true, paced: true, badge: 'NEW',
    description: '英語のふだを持って泳ぐゴトモンを、つりあげよう！', goal: 'ことばを見る → 合うふだのゴトモンをタップ → 12匹つろう！', skill: '大漁フィーバー', effect: '次の3匹の得点アップ', unit: '匹', color: '#2f7fb8',
    howTo: ['英語の意味をさがす問題と、日本語を英語にする問題が、かわりばんこに出るよ。🔊で英語が聞ける。', '合うふだを持ったゴトモンをタップすると、相棒がつりあげる。ゴトモンは止まらずに泳ぎつづけるよ。', 'ちがっても大丈夫。そのふだの意味を教えてくれて、答えのゴトモンが光るよ。'],
    controlsNote: 'Tabキーでゴトモンを選んで、Enterでもつれます。' },
  gotomonToss: { genre: '算数', difficulty: 'ふつう', time: '約3分', icon: '🧺', scene: 'toss', arcade: true, paced: true, badge: 'NEW',
    description: '動きまわるゴトモンのかごに、計算の答えをねらって玉を入れよう！', goal: '計算を見る → 答えのかごをタップ → 12球 入れよう！', skill: '玉入れフィーバー', effect: '次の3球の得点アップ', unit: '球', color: '#3f8a3a',
    howTo: ['下に出る計算の答えを考えよう。', 'その数字のかごを持っているゴトモンをタップすると、相棒が玉を投げるよ。はやく入れると得点アップ！', 'ちがうかごでも大丈夫。答えのかごが光るので、もう一度ねらおう。'],
    controlsNote: 'Tabキーでかごを選んで、Enterでも投げられます。' },
  kanjiSort: { genre: '漢字の画数・読み', difficulty: 'ふつう', time: '約3分', icon: '🧩', scene: 'sort', arcade: true, paced: true, badge: 'NEW',
    description: '漢字のカードを、画数の少ない順や読みのあいうえお順にならべよう！', goal: 'ルールを見る → つぎに入るカードをタップ → 8つのパズルを完成！', skill: 'ならべ名人', effect: '次の3問の得点アップ', unit: 'こ', color: '#5b3a8c',
    howTo: ['上のルール（画数の少ない順・読みのあいうえお順）を見て、つぎに入るカードをタップしよう。', '読みのパズルは、カードの下のことばで読みをたしかめよう。最初の音で、あいうえお順にならべるよ。', 'ちがっても、そのカードの画数や読みを教えてくれるよ。光ったカードを入れれば先に進める。'],
    controlsNote: 'Tabキーでカードを選んで、Enterでも置けます。' },
  gotomonShop: { genre: '漢字の読み・意味', difficulty: '挑戦', time: '約4分', icon: '🏪', scene: 'shop', arcade: true, paced: true, badge: 'NEW',
    description: 'ゴトモンのお客さんのおねがいを聞いて、ぴったりの漢字をわたそう！', goal: 'お客さんをえらぶ → 合う漢字をわたす → 12人のおねがいをかなえよう！', skill: '大はんじょう', effect: '次の3問の得点アップ', unit: '人', color: '#a0663a',
    howTo: ['お客さんのふきだしは、ほしい漢字の読み（黄色）か意味。タップしたお客さんのおねがいが下に出るよ。', 'たなから合う漢字をタップしてわたす。はやくわたすと😊ごきげんで、チップ⭐がふえる。', 'ちがったら、ほしい漢字のカードが光るよ。お客さんは帰らないので、あわてなくてだいじょうぶ。'],
    controlsNote: 'Tabキーでお客さんや漢字を選んで、Enterでもわたせます。' },
  kanjiMemory: { genre: '漢字の読み・意味', difficulty: 'ふつう', time: '約3分', icon: '🎴', scene: 'memory', arcade: true, paced: true, badge: 'NEW',
    description: 'カードをめくって、漢字と読み・意味のペアを見つけよう！', goal: '2まいめくる → 同じペアならそろう → 全部そろえてクリア！', skill: 'めくりの達人', effect: '次の3問の得点アップ', unit: '組', color: '#3574b6',
    howTo: ['カードを2まいめくる。漢字と、その読み（ラウンド2は意味）がそろえばペア！', 'ちがうときはカードがもどる。どこに何があったか、おぼえておこう。', '👀のぞき見で、全部のカードを少しだけ見られる。3組続けてそろえると、もう1回ふえるよ。'],
    controlsNote: 'Tabキーでカードを選んで、Enterでもめくれます。' },
  kanjiBingo: { genre: '漢字の読み・意味', difficulty: 'ふつう', time: '約3分', icon: '🎱', scene: 'bingo', arcade: true, paced: true, badge: 'NEW',
    description: '読みや意味をヒントに漢字をさがして、ビンゴをそろえよう！', goal: 'ヒントの漢字をタップ → マスがあく → 列をそろえてビンゴ！', skill: 'ビンゴチャンス', effect: '次の3問の得点アップ', unit: '問', color: '#2f6fb3',
    howTo: ['よびだしの「よみ」（黄色の読み）や「いみ」に合う漢字を、カードからさがしてタップ。', '1回で当てるとマスがあく。まちがえた漢字は、あとでもう一度よびだされるよ。', '3回続けて当てると⭐スタンプ。好きなマスをあけて、ビンゴをねらおう！'],
    controlsNote: 'Tabキーでマスを選んで、Enterでも答えられます。' },
  tripSugoroku: { genre: '漢字・ことわざ', difficulty: '挑戦', time: '約4分', icon: '🗺', scene: 'trip', arcade: true, paced: true, badge: 'NEW',
    description: '道を選んで進み、道具を集めて地方のボスに挑もう！', goal: '道を選ぶ → 問題で道具を集める → ボスに挑戦！', skill: '旅の追い風', effect: '次の3問の得点アップ', unit: '問', color: '#b0652f',
    howTo: ['分かれ道で、進むマスを選ぶ。📖読み・🔥修行・📜ことわざ・🎁宝箱・⛺休けい所。', '問題に答えて🔥ヒントの火や⭐きらきらを集める。🔥はまちがいの答えを2つ消す。', '最後は地方のボス！ ⭐を使うと2ダメージ。倒せなくても、また挑戦できるよ。'],
    controlsNote: 'キーボードの1〜4でも答えられます。' },
  kanjiDefense: { genre: '漢字の読み', difficulty: '挑戦', time: '約3分', icon: '♜', scene: 'defend', arcade: true, paced: true, badge: 'NEW',
    description: '読みを入力して、せまるモンスターを撃退！', goal: '読みを入力 → 同じ読みのモンスターに命中！', skill: '相棒エール', effect: '次の3正解で得点UP', unit: '撃退', color: '#ac5838',
    howTo: ['モンスターが持つ漢字の読みを考える。', '読みをひらがなで入れて「こうげき」。同じ読みのモンスターに自動で命中！', '門まで来ても大丈夫。読みを見て、次に生かそう。'],
    controlsNote: 'モンスターをタップすると、ねらいを決められます。' },
});
