// Presentation metadata stays outside the stable v1 registry contract.
// `arcade` games draw their own real-time world; `paced` games offer ゆっくり.
export const gameExperiences = Object.freeze({
  mathSprint: { genre: '算数', difficulty: '入門', time: '約1分', icon: '➜', scene: 'race', arcade: true, paced: true, badge: 'NEW',
    description: '計算してハードルをジャンプ！ ゴールまで走りぬけ。', goal: '答えるとジャンプ。止まらず走ってタイムを縮めよう。', skill: 'ゴトモンダッシュ', effect: '5秒間スピードアップ', unit: 'm', color: '#177a69',
    howTo: ['ハードルの計算に答えると、相棒がジャンプ！', '早く答えるほど止まらずに走れる。まちがえても前へ進めるよ。', '3回正解すると「ゴトモンダッシュ」が自動で発動！'],
    controlsNote: 'キーボードの数字とEnterでも遊べます。' },
  mathInvader: { genre: '算数', difficulty: 'ふつう', time: '約2分', icon: '✦', scene: 'shoot', arcade: true, paced: true, badge: 'NEW',
    description: '答えの数字をうつと、その敵に命中！ 最後はボス戦。', goal: '答えをうつ → 同じ答えの敵に命中！', skill: 'スター連射', effect: '次の3発を強化', unit: '撃退', color: '#346bab',
    howTo: ['落ちてくる敵の計算を見る。', '答えの数字を入れて「うつ！」。同じ答えの敵に自動で命中！', 'バリアまで来ても大丈夫。最後に出てくるボスをたおそう！'],
    controlsNote: 'キーボードの数字とEnterでも遊べます。敵をタップすると、ねらいを決められます。' },
  englishChoice: { genre: '英語', difficulty: '入門', time: '約1分', icon: '◇', scene: 'chest', arcade: true, paced: true, badge: 'NEW',
    description: '英単語の意味の宝箱をキャッチ！', goal: '意味の合う宝箱をタップ → 宝箱が開く！', skill: 'おたからフィーバー', effect: '次の3回の宝を大きく', unit: '箱', color: '#7153a4',
    howTo: ['上に出た英単語を読む。', '意味の合う宝箱をタップ！ 早くキャッチするほど宝が大きい。', '下まで落ちても大丈夫。落ち着いて選ぼう。'],
    controlsNote: 'キーボードの1〜4でも選べます。' },
  sentenceOrder: { genre: '国語', difficulty: 'ふつう', time: '約2分', icon: '▰', scene: 'bridge', arcade: true, paced: true, badge: 'NEW',
    description: 'ことばの板を順にならべて、相棒の橋をかけよう。', goal: '文の順に板をタップ → 橋ができて相棒がわたる！', skill: '虹のかけ橋', effect: '次の3本の橋を虹色に', unit: '橋', color: '#39774c',
    howTo: ['川にうかぶ言葉の板を、文のはじめから順にタップ。', '板がそろうと橋になって、相棒がわたる！ 早いほど得点アップ。', 'まちがえた板は、橋の板をタップすると川にもどせるよ。'],
    controlsNote: 'キーボードの1〜4でも選べます。' },
  timedChoice: { genre: 'ことば', difficulty: '挑戦', time: '約1分', icon: '◷', scene: 'mole', arcade: true, paced: true, badge: 'NEW',
    description: '正しい読みのもぐらをたたこう！', goal: '読みの合うもぐらをタップ → ポカッ！', skill: 'もぐらフィーバー', effect: '次の3回の得点アップ', unit: '匹', color: '#ad6726',
    howTo: ['上に出た言葉の読みを考える。', '正しい読みを持ったもぐらをたたく！ 早いほど高得点。', 'もぐらは5秒で引っこむ。引っこんでも、答えを見て次へ行こう。'],
    controlsNote: 'キーボードの1〜4でもたたけます。「ゆっくり」では8秒です。' },
  multiSelect: { genre: '理科・算数ほか', difficulty: 'ふつう', time: '約2分', icon: '✧', scene: 'stars', arcade: true, paced: true, badge: 'NEW',
    description: 'お題に合う星をぜんぶ集めて、星座をつくろう。', goal: '合う星をタップで集める → 「あつめた！」で星座に！', skill: '星のきらめき', effect: '次の3つの星座を明るく', unit: '星座', color: '#347b87',
    howTo: ['夜空に出たお題を読む。', 'お題に合う星をぜんぶタップして集める。もう一度タップでもどせる。', '集めたら「あつめた！」。早く決めるほど星座が明るい。'],
    controlsNote: 'キーボードの1〜5で星を選び、Enterで決定できます。' },
  asyncChoice: { genre: '教科ミックス', difficulty: 'ふつう', time: '約2分', icon: '⌖', scene: 'mine', arcade: true, paced: true, badge: 'NEW',
    description: '正しい線路をえらんで、トロッコで宝の洞くつへ！', goal: '答えの線路をタップ → トロッコが洞くつへ！', skill: '発見フィーバー', effect: '次の3回の宝石アップ', unit: '発見', color: '#447b67',
    howTo: ['トロッコの前に出た問題を読む。', '答えの書かれた線路をタップ！ トロッコがその洞くつへ進む。', '分かれ道に着いても、トロッコは待っていてくれる。'],
    controlsNote: 'キーボードの1〜4でも選べます。' },
  kanjiDefense: { genre: '漢字の読み', difficulty: '挑戦', time: '約3分', icon: '♜', scene: 'defend', arcade: true, paced: true, badge: 'NEW',
    description: '読みを入力して、せまるモンスターを撃退！', goal: '読みを入力 → 同じ読みのモンスターに命中！', skill: '相棒エール', effect: '次の3正解で得点UP', unit: '撃退', color: '#ac5838',
    howTo: ['モンスターが持つ漢字の読みを考える。', '読みをひらがなで入れて「こうげき」。同じ読みのモンスターに自動で命中！', '門まで来ても大丈夫。読みを見て、次に生かそう。'],
    controlsNote: 'モンスターをタップすると、ねらいを決められます。' },
});
