# Checks Codex's evolved pictures and puts them in the game as 512x512 WebP (transparent background).
# Reads <outDir>/<id>/<id>_evo.png for every target in targets.json and writes
# public/assets/images/monsters/evo/<id>.webp. Nothing is overwritten unless --force.
# A picture whose corners are not transparent is reported and skipped (fix it in Codex, then run again).
# usage: python scripts/evolution/import-images.py <outDir> [--force]
import json, sys
from pathlib import Path
from PIL import Image

out_dir = Path(sys.argv[1]); force = '--force' in sys.argv
dest = Path('public/assets/images/monsters/evo'); dest.mkdir(parents=True, exist_ok=True)
targets = json.loads(Path('scripts/evolution/targets.json').read_text(encoding='utf-8'))
for target in targets:
    gid = target['id']; src = out_dir / gid / f'{gid}_evo.png'; to = dest / f'{gid}.webp'
    if not src.exists(): print(f'{gid}: no picture yet'); continue
    if to.exists() and not force: print(f'{gid}: already in the game (use --force to replace)'); continue
    image = Image.open(src).convert('RGBA'); w, h = image.size
    # Generated pictures come with alpha like 253: make every dot fully solid or fully clear, as pixel art is.
    image.putalpha(image.getchannel('A').point(lambda a: 255 if a >= 128 else 0))
    corners = [image.getpixel(p)[3] for p in [(0, 0), (w - 1, 0), (0, h - 1), (w - 1, h - 1)]]
    if max(corners) > 10: print(f'{gid}: SKIPPED, the background is not transparent (corners alpha {corners}), {w}x{h}'); continue
    # Fit into 512x512 with the 10% margin the prompt asks for, keeping the dots sharp.
    box = image.getbbox() or (0, 0, w, h); body = image.crop(box)
    scale = min(410 / body.width, 410 / body.height)
    body = body.resize((max(1, round(body.width * scale)), max(1, round(body.height * scale))), Image.NEAREST)
    canvas = Image.new('RGBA', (512, 512), (0, 0, 0, 0))
    canvas.paste(body, ((512 - body.width) // 2, (512 - body.height) // 2), body)
    canvas.save(to, 'WEBP', lossless=True)
    print(f'{gid}: imported from {w}x{h} -> {to} ({to.stat().st_size // 1024} KB)')

# The game's list of Gotomon with an evolved picture: every WebP now in the evo folder.
ids = sorted(path.stem for path in dest.glob('*.webp'))
Path('src/minigames/evolvedIds.js').write_text(
    '// Generated by scripts/evolution/import-images.py: the Gotomon that have an evolved picture\n'
    '// (public/assets/images/monsters/evo/<id>.webp). Do not edit by hand.\n'
    f"export const EVOLVED_IDS = Object.freeze({json.dumps(ids, ensure_ascii=False)});\n", encoding='utf-8', newline='\n')
print(f'evolvedIds.js: {len(ids)}')
