import fs from 'node:fs';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
const git=(...args)=>execFileSync('git',args,{encoding:'utf8'}).trim();
const hash=file=>createHash('sha256').update(fs.readFileSync(file)).digest('hex');
assert.equal(git('branch','--show-current'),'experiment/3d-vertical-slice');
assert.equal(git('rev-parse','HEAD'),'a23285cbff2ffaf990713a38119ecfb9e897ec35');
const refs={};for(const ref of ['main','yomitabi-2d-stable-2026-09','yomitabi-2d-stable-2026-09^{}','yomitabi-3d-v0-babylon-2026-09','yomitabi-3d-v0-babylon-2026-09^{}'])refs[ref]=git('rev-parse',ref);
assert.equal(refs['main'],'2a521dd5aa747314b25e761d976bd4f880cd58c3');
assert.equal(refs['yomitabi-2d-stable-2026-09'],'6fcd0afd23b0066a4f46f1a4169e01c98f490c06');
assert.equal(refs['yomitabi-3d-v0-babylon-2026-09'],'76e5c7210888ba5f3bf79b86d5e35be86f5b3158');
assert.equal(refs['yomitabi-3d-v0-babylon-2026-09^{}'],'15ee0be672ca8ec56e773a75959ce9535877cb19');
const changed=git('diff','--name-only','HEAD').split('\n').filter(Boolean);
assert.deepEqual(changed.sort(),['package-lock.json','package.json','src/visuals/battleVisualAdapter.js']);
assert.equal(git('diff','--cached','--name-only'),'');git('diff','--check');
const old=JSON.parse(git('show','HEAD:package-lock.json')),lock=JSON.parse(fs.readFileSync('package-lock.json','utf8'));
for(const [name,pkg]of Object.entries(old.packages))if(name)assert.deepEqual(lock.packages[name],pkg,name);
const added=Object.keys(lock.packages).filter(k=>!old.packages[k]);
assert.deepEqual(added.sort(),['node_modules/@babylonjs/loaders','node_modules/babylonjs-gltf2interface']);
assert.equal(lock.packages['node_modules/@babylonjs/loaders'].version,'9.25.0');
const asset='public/assets/3d/monsters/HKD-E01/HKD-E01.v1a.1.glb';
assert.equal(hash(asset),'da77cb290755bd40005004ecb4b036b8ac4f268888de29cd37b952bd44048d7f');
const files={};for(const dir of ['src/visuals','tests/v1a','tools/v1a'])for(const name of fs.readdirSync(dir))if(fs.statSync(dir+'/'+name).isFile())files[dir+'/'+name]=hash(dir+'/'+name);
files[asset]=hash(asset);files['YOMITABI_3D_V1A_GLB_INTEGRATION_REPORT.md']=hash('YOMITABI_3D_V1A_GLB_INTEGRATION_REPORT.md');
const regression=JSON.parse(fs.readFileSync('artifacts/v1a/regression/regression.json','utf8'));
for(const r of regression)assert.equal(r.exit,0);
assert.equal(regression.slice(0,4).reduce((n,x)=>n+x.pass,0),268);
assert.equal(regression.find(x=>x.name==='v0').pass,23);assert.equal(regression.find(x=>x.name==='v1a').pass,35);
for(const r of regression.filter(x=>'tests'in x))for(const key of ['fail','cancelled','skipped','todo'])assert.equal(r[key],0);
const evidence={at:new Date().toISOString(),refs,changed,added,assetSHA:hash(asset),regression,files,pass:true};
fs.writeFileSync('artifacts/v1a/final-audit.json',JSON.stringify(evidence,null,2));console.log('V1a final source / refs / dependency / regression audit PASS');
