import fs from 'node:fs';
import path from 'node:path';
const role=process.argv[2]||'baseline';
const root=path.resolve(role==='baseline'?'../baseline-2d':'.','dist/assets');
export const bundle=fs.readdirSync(root).find(n=>/^index-.*\.js$/.test(n));
const source=fs.readFileSync(path.join(root,bundle),'utf8');
const one=(regex)=>{const all=[...source.matchAll(regex)];if(all.length!==1)throw Error('Nonunique landmark '+regex+' '+all.length);return all[0];};
const sessionPoint=one(/([\w$]+)\.wrongKanjiList=\[\],\1\.correctKanjiList=\[\],([\w$]+)=([\w$]+)\(\),typeof window/g);
const ready=one(/function ([\w$]+)\(\)\{return ([\w$]+)!==null&&[\w$]+\(\2\)\}/g);
const recorded=one(/let [\w$]+=0,([\w$]+)=new WeakSet,([\w$]+)=new WeakSet/g);
const session=one(/source:[\w$]+,session:([\w$]+)\}\}function/g);
const battle=one(/([\w$]+)\.enemyActionTimer>0&&\(\1\.enemyActionTimer=/g);
const screen=one(/([\w$]+)=\{canvas:null,ctx:null,inputEl:null,victoryCallback:null,stageBgImage:null/g);
const buttons=one(/([\w$]+)=\{back:\{x:20,y:20,w:100,h:30,label:"タイトルへ"\},stage:/g);
const images=one(/this\.stageBgImage=([\w$]+)\[`bg_\$\{/g);
export const names={game:sessionPoint[1],battle:battle[1],screen:screen[1],buttons:buttons[1],images:images[1],recorded:recorded[1],session:session[1],ready:ready[1]};
const offset=sessionPoint.index+sessionPoint[0].indexOf('typeof window');
const pre=source.slice(0,offset);
export const points={session:{lineNumber:pre.split('\n').length-1,columnNumber:offset-(pre.lastIndexOf('\n')+1),offset,context:source.slice(offset-80,offset+100)}};
if(process.argv[1]?.endsWith('source-points.mjs'))console.log({bundle,names,points});
