// Short cross-subject questions. First option is correct in source, shuffled at runtime.
export const ASYNC_CONTENT_ADDITIONS = Object.freeze([
  ['right-angle','直角は何度？','90度|45度|180度|360度','math.geometry'],
  ['triangle-sum','三角形の内角の和は？','180度|90度|270度|360度','math.geometry'],
  ['quadrilateral-sum','四角形の内角の和は？','360度|90度|180度|540度','math.geometry'],
  ['diameter','円の直径は半径の何倍？','2倍|3倍|4倍|半分','math.geometry'],
  ['one-meter','1mは何cm？','100cm|10cm|1000cm|1cm','math.measure'],
  ['one-kilogram','1kgは何g？','1000g|10g|100g|10000g','math.measure'],
  ['one-liter','1Lは何mL？','1000mL|10mL|100mL|10000mL','math.measure'],
  ['one-hour','1時間は何分？','60分|30分|100分|120分','math.measure'],
  ['one-minute','1分は何秒？','60秒|10秒|30秒|100秒','math.measure'],
  ['square-meter','1平方mは何平方cm？','10000平方cm|10平方cm|100平方cm|1000平方cm','math.measure'],
  ['decimal-half','0.5と同じ大きさの分数は？','1/2|1/5|5/1|1/10','math.decimals'],
  ['fraction-add','1/4 + 2/4 は？','3/4|3/8|2/4|1/4','math.fractions'],
  ['numerator','3/5の分子は？','3|5|8|2','math.fractions'],
  ['even-definition','偶数とはどんな整数？','2で割り切れる|必ず3で割り切れる|必ず5で割り切れる|すべて1けた','math.numbers'],
  ['six-times-eight','6 × 8 は？','48|42|54|14','math.multiply'],
  ['divide-six','24 ÷ 6 は？','4|6|18|30','math.divide'],
  ['average','4、6、8の平均は？','6|4|8|18','math.statistics'],
  ['mode','2、3、3、5の最頻値は？','3|2|5|13','math.statistics'],
  ['perimeter','縦3cm、横5cmの長方形の周りは？','16cm|8cm|15cm|30cm','math.geometry'],
  ['square-sides','正方形の4辺の長さは？','すべて等しい|すべて違う|2辺だけ等しい|決まっていない','math.geometry'],
  ['heart','血液を送り出すポンプの役目は？','心臓|胃|小腸|食道','science.body'],
  ['lung','呼吸で体内から出す主な不要な気体は？','二酸化炭素|水素|ヘリウム|メタン','science.body'],
  ['small-intestine','養分を主に吸収する器官は？','小腸|食道|気管|心臓','science.body'],
  ['kidney','尿をつくる器官は？','腎臓|心臓|肺|食道','science.body'],
  ['stomata','葉の表面で気体が出入りする穴は？','気孔|根毛|道管|種子','science.plants'],
  ['burning-gas','ものが燃えるのを助ける気体は？','酸素|窒素|二酸化炭素|ヘリウム','science.matter'],
  ['air-nitrogen','空気に最も多い気体は？','窒素|酸素|二酸化炭素|水素','science.matter'],
  ['water-formula','水の化学式は？','H₂O|CO₂|O₂|NaCl','science.matter'],
  ['boiling-water','1気圧で水が沸騰する温度は？','約100℃|約0℃|約50℃|約200℃','science.matter'],
  ['reflection','鏡で反射角と入射角の大きさは？','等しい|反射角が必ず2倍|入射角が必ず2倍|常に違う','science.energy'],
  ['vacuum-sound','真空中で音は伝わる？','伝わらない|速く伝わる|高い音だけ伝わる|低い音だけ伝わる','science.energy'],
  ['magnet-poles','磁石のN極どうしを近づけると？','しりぞけ合う|引き合う|必ずくっつく|極が消える','science.matter'],
  ['frozen-volume','水が氷になると体積は？','増える|減る|必ず半分|変わらない','science.matter'],
  ['plant-producer','光合成で養分をつくる生物は？','アサガオ|ウサギ|カブトムシ|ミミズ','science.plants'],
  ['earth-rotation','地球が1回自転する時間は？','約1日|約1時間|約1か月|約1年','science.space'],
  ['earth-revolution','地球が太陽を1周する時間は？','約1年|約1日|約1週間|約1か月','science.space'],
  ['moon-reflection','月が明るく見える主な理由は？','太陽の光を反射|月で火が燃える|地球が発光する|星を飲みこむ','science.space'],
  ['sun-star','太陽のように自ら光る星は？','恒星|惑星|衛星|小惑星','science.space'],
  ['root-water','植物が土から水を吸う部分は？','根|花びら|種子|実','science.plants'],
  ['pollen','花粉をつくる部分は？','おしべ|めしべの先|がく|花びら','science.plants'],
  ['equator','緯度0度の線を何という？','赤道|本初子午線|北極線|日付変更線','social.geography'],
  ['prime-meridian','経度0度の線を何という？','本初子午線|赤道|北回帰線|南回帰線','social.geography'],
  ['map-scale','地図の縮尺が表すものは？','実際を縮めた割合|土地の高さ|雨の量|人口の多さ','social.maps'],
  ['contour','等高線が結ぶ場所は？','高さが等しい場所|雨量が等しい場所|人口が等しい場所|気温が等しい場所','social.maps'],
  ['opposite-north','北の反対の方角は？','南|東|西|北東','social.maps'],
  ['east-on-map','北が上の地図で東はどちら？','右|左|上|下','social.maps'],
  ['largest-island','日本で最も面積が大きい島は？','本州|北海道|九州|四国','social.geography'],
  ['japan-sea','日本と朝鮮半島の間にある海は？','日本海|地中海|紅海|カリブ海','social.geography'],
  ['highest-mountain','日本で最も高い山は？','富士山|筑波山|阿蘇山|六甲山','social.geography'],
  ['longest-river','日本で最も長い川は？','信濃川|利根川|石狩川|木曽川','social.geography'],
  ['largest-lake','日本で最も面積が大きい湖は？','琵琶湖|霞ヶ浦|サロマ湖|猪苗代湖','social.geography'],
  ['industrial-product','工業製品はどれ？','自動車|米|サンマ|しいたけ','social.industry'],
  ['hydroelectric','流れる水の力を使う発電は？','水力発電|火力発電|太陽光発電|地熱発電','science.energy'],
  ['thermal-power','石炭などを燃やす発電は？','火力発電|風力発電|水力発電|太陽光発電','science.energy'],
  ['solar-power','太陽光発電が利用するものは？','太陽の光|風|波|地中の熱','science.energy'],
  ['legislature','日本で法律をつくる機関は？','国会|裁判所|消防署|図書館','social.civics'],
  ['judiciary','日本で司法を担う機関は？','裁判所|国会|郵便局|図書館','social.civics'],
  ['executive','日本で行政権が属する機関は？','内閣|国会|最高裁判所|博物館','social.civics'],
  ['written-source','昔の文字の記録を調べる資料は？','古文書|雲の写真|気温計|種子','social.history'],
  ['kofun','古墳は主に何のために作られた？','有力者の墓|学校|市場|港','social.history'],
  ['adjective-beautiful','「美しい」の品詞は？','形容詞|名詞|動詞|接続詞','japanese.grammar'],
  ['adjectival-quiet','「静かだ」の品詞は？','形容動詞|名詞|形容詞|副詞','japanese.grammar'],
  ['adverb-very','「とても」の品詞は？','副詞|名詞|動詞|助詞','japanese.grammar'],
  ['conjunction-but','「しかし」の品詞は？','接続詞|名詞|動詞|形容詞','japanese.grammar'],
  ['demonstrative','こそあど言葉はどれ？','それ|歩く|楽しい|静かだ','japanese.grammar'],
  ['subject','「鳥が空を飛ぶ」の主語は？','鳥が|空を|飛ぶ|空','japanese.grammar'],
  ['predicate','「猫が眠る」の述語は？','眠る|猫が|猫|が','japanese.grammar'],
  ['modifier','「赤い花が咲く」で花を修飾する語は？','赤い|花が|咲く|が','japanese.grammar'],
  ['phrase-count','「雨が降る」は何文節？','2文節|1文節|3文節|4文節','japanese.grammar'],
  ['tanka-count','短歌の基本の音数は？','31音|17音|20音|35音','japanese.poetry'],
  ['haiku-count','俳句の基本の音数は？','17音|31音|10音|50音','japanese.poetry'],
  ['season-word','季語とは何を表す言葉？','季節|文の主語|反対の意味|文の長さ','japanese.poetry'],
  ['period','句点はどれ？','。|、|？|！','japanese.punctuation'],
  ['comma','読点はどれ？','、|。|？|！','japanese.punctuation'],
  ['opposite-start','「開始」の反対の意味は？','終了|発見|出発|準備','japanese.vocabulary'],
  ['opposite-success','「成功」の反対の意味は？','失敗|努力|達成|進歩','japanese.vocabulary'],
  ['opposite-agree','「賛成」の反対の意味は？','反対|協力|安心|承認','japanese.vocabulary'],
  ['sea-radical','「海」の部首は？','さんずい|きへん|にんべん|ごんべん','japanese.kanji'],
  ['talk-okurigana','「話す」の送り仮名は？','す|話|はな|はなす','japanese.kanji'],
  ['lend-hand','「手を貸す」の意味は？','手伝う|手を洗う|腕を伸ばす|握手する','japanese.idiom'],
  ['be-he','He ___ my friend. 空欄に入るのは？','is|am|are|be','english.grammar'],
  ['be-i','I ___ a student. 空欄に入るのは？','am|is|are|be','english.grammar'],
  ['be-they','They ___ happy. 空欄に入るのは？','are|am|is|be','english.grammar'],
  ['article-apple','appleの前に置く不定冠詞は？','an|a|the|these','english.grammar'],
  ['plural-child','childの複数形は？','children|childs|childes|childrens','english.grammar'],
  ['past-eat','eatの過去形は？','ate|eaten|eating|eats','english.grammar'],
  ['past-see','seeの過去形は？','saw|seen|seeing|sees','english.grammar'],
  ['after-can','canのすぐ後の動詞はどの形？','原形|過去形|ing形|三単現のs形','english.grammar'],
  ['where','場所をたずねる疑問詞は？','where|when|who|why','english.grammar'],
  ['when','時をたずねる疑問詞は？','when|where|who|why','english.grammar'],
  ['how-many','How manyでたずねるのは？','数|場所|理由|人の名前','english.grammar'],
  ['english-thanks','Thank you. の意味は？','ありがとう|おやすみ|はじめまして|さようなら','english.vocabulary'],
  ['english-excuse','Excuse me. と声をかける意味は？','すみません|いただきます|おめでとう|おやすみ','english.vocabulary'],
  ['english-weather','天気を表す英単語は？','weather|window|winter|water','english.vocabulary'],
  ['english-country','国を表す英単語は？','country|city|village|town','english.vocabulary'],
  ['english-thousand','thousandが表す数は？','1000|100|10|10000','english.vocabulary'],
  ['english-left','leftの「方向」の意味は？','左|右|上|下','english.vocabulary'],
  ['english-between','betweenの場所を表す意味は？','〜の間に|〜の上に|〜の下に|〜の後ろに','english.vocabulary'],
  ['english-before','beforeの「時間」の意味は？','〜より前に|〜の間に|〜の後に|〜と同時に','english.vocabulary'],
  ['english-because','理由を述べる接続詞は？','because|but|or|and','english.grammar'],
].map(([id,prompt,options,skillId])=>Object.freeze({id,prompt,options:Object.freeze(options.split('|')),skillId})));
