// Author-reviewed everyday vocabulary. Each row is a distinct word and meaning.
export const ENGLISH_CONTENT_ADDITIONS = Object.freeze([
  ['pencil','えんぴつ','school'], ['eraser','消しゴム','school'],
  ['desk','机','school'], ['chair','いす','school'],
  ['teacher','先生','school'], ['student','生徒','school'],
  ['classroom','教室','school'], ['notebook','ノート','school'],
  ['ruler','定規','school'], ['dictionary','辞書','school'],
  ['mother','母','home'], ['father','父','home'],
  ['sister','姉・妹','home'], ['brother','兄・弟','home'],
  ['kitchen','台所','home'], ['window','窓','home'],
  ['door','ドア','home'], ['bed','ベッド','home'],
  ['clock','時計','home'], ['garden','庭','home'],
  ['bread','パン','food'], ['rice','米','food'],
  ['milk','牛乳','food'], ['egg','卵','food'],
  ['cheese','チーズ','food'], ['fish','魚','food'],
  ['meat','肉','food'], ['potato','じゃがいも','food'],
  ['carrot','にんじん','food'], ['tomato','トマト','food'],
  ['banana','バナナ','food'], ['grape','ぶどう','food'],
  ['peach','桃','food'], ['lemon','レモン','food'],
  ['soup','スープ','food'], ['salt','塩','food'],
  ['sugar','砂糖','food'], ['breakfast','朝食','food'],
  ['lunch','昼食','food'], ['dinner','夕食','food'],
  ['mountain','山','nature'], ['river','川','nature'],
  ['forest','森','nature'], ['sea','海','nature'],
  ['sky','空','nature'], ['cloud','雲','nature'],
  ['rain','雨','nature'], ['snow','雪','nature'],
  ['wind','風','nature'], ['flower','花','nature'],
  ['tree','木','nature'], ['bird','鳥','nature'],
  ['rabbit','うさぎ','nature'], ['horse','馬','nature'],
  ['turtle','かめ','nature'], ['butterfly','ちょう','nature'],
  ['spring','春','time'], ['summer','夏','time'],
  ['autumn','秋','time'], ['winter','冬','time'],
  ['today','今日','time'], ['yesterday','昨日','time'],
  ['tomorrow','明日','time'], ['week','週','time'],
  ['year','年','time'], ['noon','正午','time'],
  ['station','駅','place'], ['hospital','病院','place'],
  ['library','図書館','place'], ['park','公園','place'],
  ['museum','博物館','place'], ['bridge','橋','place'],
  ['walk','歩く','action'], ['swim','泳ぐ','action'],
  ['write','書く','action'], ['speak','話す','action'],
  ['listen','耳を傾ける','action'], ['sleep','眠る','action'],
  ['buy','買う','action'], ['sell','売る','action'],
  ['open','開ける','action'], ['close','閉める','action'],
  ['wash','洗う','action'], ['carry','運ぶ','action'],
  ['sing','歌う','action'], ['dance','おどる','action'],
  ['sad','悲しい','feeling'], ['angry','怒っている','feeling'],
  ['hungry','おなかがすいた','feeling'], ['thirsty','のどがかわいた','feeling'],
  ['tired','疲れた','feeling'], ['busy','忙しい','adjective'],
  ['long','長い','adjective'], ['short','短い','adjective'],
  ['heavy','重い','adjective'], ['light','軽い','adjective'],
  ['new','新しい','adjective'], ['old','古い','adjective'],
  ['fast','速い','adjective'], ['slow','遅い','adjective'],
].map(([word,meaning,category]) => Object.freeze({word,meaning,category,difficulty:'standard'})));

const originalCategories = {
  apple:'food',book:'school',cat:'nature',dog:'nature',sun:'nature',moon:'nature',water:'nature',
  school:'school',friend:'home',family:'home',red:'adjective',blue:'adjective',
  run:'action',eat:'action',read:'action',happy:'feeling',big:'adjective',small:'adjective',morning:'time',night:'time',
};
const categories = new Map([...Object.entries(originalCategories),...ENGLISH_CONTENT_ADDITIONS.map(q=>[q.word,q.category])]);
export const englishCategory = word => categories.get(word);
