// Writes src/minigames/breedingRecipes.js: one fixed recipe per legendary Gotomon (はいごう, 2026-10-02).
// A recipe is "a Gotomon of type A from the legend's region (Lv5+) + a Gotomon of type B from anywhere (Lv5+)".
// Type A is only a type that region has at least 3 ordinary Gotomon of, so every recipe can be made.
// usage: node --experimental-default-type=module scripts/breeding/gen-recipes.mjs   (from the repo root)
import { readFileSync, writeFileSync } from 'node:fs';
import { typeOf, GOTOMON_TYPES } from '../../src/minigames/gotomonTypes.js';
import { LEGEND_REGION_BY_PREFIX, regionOfStage } from '../../src/minigames/breedingRegions.js';

const data = file => JSON.parse(readFileSync(`public/data/${file}`, 'utf8')).flat(Infinity).filter(m => m?.id);
const legends = data('enemies_legend.json'), legendIds = new Set(legends.map(m => m.id));
const ordinary = new Map([...data('enemies_proto.json'), ...data('enemy_world.json')].filter(m => !legendIds.has(m.id)).map(m => [m.id, m]));
const order = GOTOMON_TYPES.map(type => type.id);
const counts = {};
for (const m of ordinary.values()) {
  const region = regionOfStage(m.stageId); if (!region) continue;
  (counts[region] ??= {})[typeOf(m)] = (counts[region][typeOf(m)] ?? 0) + 1;
}
// B: the legend's own kind first (でんせつ), then the common types.
const PARTNERS = ['legend', 'food', 'nature', 'fest', 'history', 'craft'];
const recipes = {}, perRegion = {};
for (const legend of legends) {
  const region = LEGEND_REGION_BY_PREFIX[legend.id.split('-')[0]];
  if (!region) throw new Error(`no region for ${legend.id}`);
  const home = Object.entries(counts[region]).filter(([type, n]) => type !== 'odd' && n >= 3)
    .sort((x, y) => y[1] - x[1] || order.indexOf(x[0]) - order.indexOf(y[0])).map(([type]) => type);
  const pairs = PARTNERS.flatMap(b => home.map(a => [a, b]));
  const index = perRegion[region] = (perRegion[region] ?? -1) + 1;
  if (index >= pairs.length) throw new Error(`not enough recipes for ${region}`);
  recipes[legend.id] = { region, a: pairs[index][0], b: pairs[index][1] };
}
const lines = Object.entries(recipes).map(([id, r]) => `  '${id}': ['${r.region}', '${r.a}', '${r.b}'],`);
writeFileSync('src/minigames/breedingRecipes.js', `// Generated by scripts/breeding/gen-recipes.mjs — do not edit by hand (run the script again).
// legend id: [region, type A (a Gotomon of the region), type B (any Gotomon)].
export const RECIPES = Object.freeze({
${lines.join('\n')}
});
`);
console.log(`recipes: ${Object.keys(recipes).length}`, JSON.stringify(perRegion));
